title: Jen Smith's Git Portfolio
description: As a technical writer learning Linux and GibHub, this space hosts some samples of my technical writing work.
theme: just-the-docs

url: https://https://github.com/jenpetsmit/jenpetsmit.github.io/jens-portfolio

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template



